_test1:
  pattern: /test1
  defaults: { _controller: PegasusTestBundle:Test:index }
_testmails:
  pattern: /mail
  defaults: { _controller: PegasusTestBundle:Test:mail }
_form1:
  pattern: /form1
  defaults: { _controller: PegasusTestBundle:Default:new }